### ISSUE TITLE
Controller-tools-gen 0.11.2 does not work with golang 1.22

### ISSUE THREAD

**Issue by smuda** [Keyfactor/ejbca-cert-manager-issuer#26]
Controller-tools-gen 0.11.2 does not work with golang 1.22 and creates a golang panic. Version 0.14 and later works better.

<details>
<summary>Golang panic</summary>

```shell
% make
mkdir -p "<redacted>/ejbca-cert-manager-issuer/bin"
test -s "<redacted>/ejbca-cert-manager-issuer/bin"/controller-gen && "<redacted>/ejbca-cert-manager-issuer/bin"/controller-gen --version | grep -q v0.11.1 || \
	GOBIN="<redacted>/ejbca-cert-manager-issuer/bin" go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.11.1
"<redacted>/ejbca-cert-manager-issuer/bin"/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x107e35af]

goroutine 28 [running]:
go/types.(*Checker).handleBailout(0xc0012ca600, 0xc0014ebd40)
	/usr/local/Cellar/go/1.22.2/libexec/src/go/types/check.go:367 +0x88
panic({0x10ad8560?, 0x1108de70?})
	/usr/local/Cellar/go/1.22.2/libexec/src/runtime/panic.go:770 +0x132
go/types.(*StdSizes).Sizeof(0x0, {0x10ba2e50, 0x110965c0})
	/usr/local/Cellar/go/1.22.2/libexec/src/go/types/sizes.go:228 +0x30f
go/types.(*Config).sizeof(...)
	/usr/local/Cellar/go/1.22.2/libexec/src/go/types/sizes.go:333
go/types.representableConst.func1({0x10ba2e50?, 0x110965c0?})
	/usr/local/Cellar/go/1.22.2/libexec/src/go/types/const.go:76 +0x9e
go/types.representableConst({0x10ba9090, 0x110627a0}, 0xc0012ca600, 0x110965c0, 0xc0014eb4b0)
	/usr/local/Cellar/go/1.22.2/libexec/src/go/types/const.go:92 +0x192
go/types.(*Checker).representation(0xc0012ca600, 0xc0014ed000, 0x110965c0)
	/usr/local/Cellar/go/1.22.2/libexec/src/go/types/const.go:256 +0x65
go/types.(*Checker).implicitTypeAndValue(0xc0012ca600, 0xc0014ed000, {0x10ba2e78, 0xc000306cb0})
	/usr/local/Cellar/go/1.22.2/libexec/src/go/types/expr.go:375 +0x2d7
go/types.(*Checker).assignment(0xc0012ca600, 0xc0014ed000, {0x10ba2e78, 0xc000306cb0}, {0x1091a3d1, 0x14})
	/usr/local/Cellar/go/1.22.2/libexec/src/go/types/assignments.go:52 +0x2e5
go/types.(*Checker).initConst(0xc0012ca600, 0xc00149e3c0, 0xc0014ed000)
	/usr/local/Cellar/go/1.22.2/libexec/src/go/types/assignments.go:126 +0x2c5
go/types.(*Checker).constDecl(0xc0012ca600, 0xc00149e3c0, {0x10ba5a20, 0xc0012b6160}, {0x10ba5a20, 0xc0012b6180}, 0x0)
	/usr/local/Cellar/go/1.22.2/libexec/src/go/types/decl.go:490 +0x311
go/types.(*Checker).objDecl(0xc0012ca600, {0x10bae1e0, 0xc00149e3c0}, 0x0)
	/usr/local/Cellar/go/1.22.2/libexec/src/go/types/decl.go:191 +0xa49
go/types.(*Checker).packageObjects(0xc0012ca600)
	/usr/local/Cellar/go/1.22.2/libexec/src/go/types/resolver.go:693 +0x4dd
go/types.(*Checker).checkFiles(0xc0012ca600, {0xc000f09cb0, 0x5, 0x5})
	/usr/local/Cellar/go/1.22.2/libexec/src/go/types/check.go:408 +0x1a5
go/types.(*Checker).Files(...)
	/usr/local/Cellar/go/1.22.2/libexec/src/go/types/check.go:372
sigs.k8s.io/controller-tools/pkg/loader.(*loader).typeCheck(0xc000363050, 0xc000125b80)
	<redacted>/go/pkg/mod/sigs.k8s.io/controller-tools@v0.11.1/pkg/loader/loader.go:286 +0x36a
sigs.k8s.io/controller-tools/pkg/loader.(*Package).NeedTypesInfo(0xc000125b80)
	<redacted>/go/pkg/mod/sigs.k8s.io/controller-tools@v0.11.1/pkg/loader/loader.go:99 +0x39
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check(0xc000bb4de0, 0xc000125b80)
	<redacted>/go/pkg/mod/sigs.k8s.io/controller-tools@v0.11.1/pkg/loader/refs.go:268 +0x2b7
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check.func1(0x0?)
	<redacted>/go/pkg/mod/sigs.k8s.io/controller-tools@v0.11.1/pkg/loader/refs.go:262 +0x53
created by sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check in goroutine 92
	<redacted>/go/pkg/mod/sigs.k8s.io/controller-tools@v0.11.1/pkg/loader/refs.go:260 +0x1c5
make: *** [manifests] Error 2

```
</details>

**Comment by smuda** [comment]
Is there anything I can do to move this issue with MR forward?
